# Generated by Django 6.0.2 on 2026-02-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('othername', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('segundoapellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('cargo', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('numero_identificacion', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
