# Generated by Django 6.0.2 on 2026-02-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='numero_identificacion',
            new_name='numberEmployee',
        ),
    ]
